=== azderbeltn/streetshift/contracts/schemas/Business.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://streetshift.dev/schemas/Business.json",
  "title": "Business",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "lng": {
      "type": "number"
    },
    "lat": {
      "type": "number"
    },
    "rating": {
      "type": [
        "number",
        "null"
      ]
    },
    "reviewCount": {
      "type": [
        "integer",
        "null"
      ]
    },
    "popularTimes": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "array",
        "items": {
          "type": "number",
          "minimum": 0,
          "maximum": 100
        }
      }
    },
    "carDependence": {
      "type": "number",
      "minimum": 0,
      "maximum": 1
    },
    "segmentId": {
      "type": "string"
    }
  },
  "required": [
    "id",
    "name",
    "category",
    "lng",
    "lat",
    "rating",
    "reviewCount",
    "popularTimes",
    "carDependence",
    "segmentId"
  ],
  "additionalProperties": false
}

=== azderbeltn/streetshift/sim/assets/hayes_valley/businesses.json
[{"id": "ChIJwW78QWKBhYARmwALRiw5sXQ", "name": "PrimeBird (pop-up)", "category": "American restaurant", "lng": -122.4228149, "lat": 37.7766142, "rating": null, "reviewCount": null, "popularTimes": null, "carDependence": 0.24, "segmentId": "65329081_5352469999"}, {"id": "ChIJD3mqz-OBhYARDrmCCkZBGVQ", "name": "The Gambit", "category": "Restaurant", "lng": -122.4260054, "lat": 37.7763404, "rating": 4.6, "reviewCount": 104, "popularTimes": null, "carDependence": 0.025, "segmentId": "65318993_2568380114"}, {"id": "ChIJgaqMEZ-AhYARektJ_RuUq4E", "name": "Baiano SF Pizza Hayes Valley", "category": "Pizza restaurant", "lng": -122.4222984, "lat": 37.7742529, "rating": 4.2, "reviewCount": 314, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 28, 31, 25, 25, 21, 34, 40, 37, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 46, 56, 53, 53, 40, 28, 18, 25, 46, 59, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 34, 46, 59, 68, 68, 53, 43, 37, 28, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 50, 56, 50, 50, 62, 87, 96, 84, 65, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 28, 59, 87, 100, 84, 50, 46, 53, 62, 50, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 28, 31, 34, 37, 40, 34, 18, 18, 15, 25, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 40, 28, 25, 21, 25, 21, 15, 12, 18, 0, 0, 0]], "carDependence": 0.635, "segmentId": "65304898_65329076"}, {"id": "ChIJYylUCqKAhYAROkTAckCGBgE", "name": "Juice Shop", "category": "Juice shop", "lng": -122.4241697, "lat": 37.7764703, "rating": 4.4, "reviewCount": 72, "popularTimes": null, "carDependence": 0.027, "segmentId": "65329081_298082887"}, {"id": "ChIJDQx5mOCAhYARniFSiz9LPqA", "name": "Maker Studio Kids", "category": "Art studio", "lng": -122.424729, "lat": 37.7778478, "rating": 5, "reviewCount": 8, "popularTimes": null, "carDependence": 0.092, "segmentId": "65351431_65351433"}, {"id": "ChIJH22heKKAhYARr6lbxkSf81U", "name": "Double Decker", "category": "Hamburger restaurant", "lng": -122.4238787, "lat": 37.7776169, "rating": 4.2, "reviewCount": 452, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 59, 64, 74, 83, 75, 77, 64, 61, 57, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 62, 68, 72, 68, 62, 59, 57, 62, 62, 61, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 55, 74, 98, 81, 64, 57, 48, 50, 57, 57, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44, 50, 50, 48, 55, 62, 59, 55, 57, 48, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 51, 62, 61, 62, 61, 68, 59, 46, 37, 29, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 77, 85, 74, 48, 31, 31, 38, 59, 75, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 66, 92, 100, 83, 79, 62, 59, 53, 48, 48, 0, 0, 0]], "carDependence": 0.358, "segmentId": "65351431_5352470004"}, {"id": "ChIJkSuevweBhYARZaPjn-d6F2w", "name": "Prelude at the Opera House", "category": "Restaurant", "lng": -122.4203163, "lat": 37.7784816, "rating": 3.4, "reviewCount": 9, "popularTimes": null, "carDependence": 0.12, "segmentId": "65352344_65356392"}, {"id": "ChIJD9JZHLKBhYARiiHQH3m_8UM", "name": "Pokebola", "category": "Restaurant", "lng": -122.4198501, "lat": 37.7760628, "rating": 3.6, "reviewCount": 134, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 58, 70, 52, 47, 29, 35, 41, 58, 64, 52, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 82, 70, 64, 70, 70, 58, 58, 64, 82, 64, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 47, 52, 64, 76, 88, 94, 58, 52, 52, 70, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 58, 70, 76, 64, 70, 64, 58, 52, 41, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 70, 52, 47, 41, 52, 52, 58, 47, 47, 29, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 58, 52, 70, 58, 70, 76, 100, 100, 100, 82, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 52, 52, 58, 52, 64, 88, 88, 94, 100, 88, 0, 0, 0]], "carDependence": 0.031, "segmentId": "65310795_65354072"}, {"id": "ChIJs78Bn8yBhYARyl8b2N91Lp8", "name": "The Epicurean Trader", "category": "Gourmet grocery store", "lng": -122.4238951, "lat": 37.7766464, "rating": 4.3, "reviewCount": 120, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 68, 87, 75, 68, 62, 75, 68, 75, 68, 87, 68, 68, 37, 43, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 43, 50, 62, 68, 62, 75, 75, 81, 68, 68, 68, 75, 62, 62, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 68, 43, 31, 37, 37, 50, 43, 43, 56, 68, 50, 50, 43, 75, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 43, 50, 37, 37, 31, 50, 50, 62, 43, 31, 37, 37, 50, 31, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 43, 43, 62, 81, 75, 68, 62, 43, 37, 56, 50, 56, 62, 43, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 37, 37, 43, 56, 56, 68, 56, 50, 37, 50, 75, 75, 87, 81, 81, 0, 0], [0, 0, 0, 0, 0, 0, 0, 62, 56, 81, 93, 100, 75, 56, 56, 50, 50, 31, 31, 37, 56, 68, 0, 0]], "carDependence": 0.588, "segmentId": "2568380114_5352469999"}, {"id": "ChIJ8bDaKgCBhYARjmm6BoQ_zms", "name": "RT Bistro", "category": "Restaurant", "lng": -122.4229511, "lat": 37.7748399, "rating": 4.3, "reviewCount": 107, "popularTimes": null, "carDependence": 0.023, "segmentId": "298082885_5352469988"}, {"id": "ChIJW0ElwaWBhYAR_R_RfKKF3ak", "name": "Hahdough German Bakery", "category": "Bakery", "lng": -122.4263128, "lat": 37.7758257, "rating": 4.6, "reviewCount": 65, "popularTimes": null, "carDependence": 0.028, "segmentId": "65284974_65318991"}, {"id": "ChIJZ4bnQTSBhYAR2jpJ472WwiE", "name": "The Italian Homemade Company (Hayes Valley)", "category": "Italian restaurant", "lng": -122.4209357, "lat": 37.7744007, "rating": 4.4, "reviewCount": 656, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 45, 62, 65, 65, 60, 52, 60, 72, 57, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 45, 45, 45, 47, 50, 60, 55, 62, 60, 50, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 57, 75, 70, 60, 57, 65, 75, 85, 77, 65, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 57, 70, 75, 70, 65, 67, 72, 62, 42, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 65, 80, 77, 60, 60, 62, 80, 92, 72, 47, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 82, 87, 80, 77, 80, 77, 82, 87, 95, 85, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 60, 80, 87, 82, 85, 92, 97, 100, 85, 0, 0, 0]], "carDependence": 0.705, "segmentId": "65304896_65350736"}, {"id": "ChIJLw3ApJiAhYAR_wGEbwDJDgE", "name": "Papito Hayes", "category": "Mexican restaurant", "lng": -122.4234085, "lat": 37.7767098, "rating": 4.4, "reviewCount": 1323, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 55, 66, 75, 70, 67, 67, 68, 61, 42, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 33, 42, 46, 44, 48, 45, 51, 57, 58, 54, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 15, 22, 28, 33, 35, 38, 54, 64, 70, 51, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 35, 37, 40, 33, 33, 38, 49, 51, 46, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 28, 42, 42, 42, 48, 59, 74, 68, 54, 49, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 49, 61, 58, 58, 54, 67, 94, 100, 90, 67, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 53, 59, 67, 68, 81, 90, 92, 79, 64, 45, 0, 0]], "carDependence": 0.029, "segmentId": "2568380114_5352469999"}, {"id": "ChIJ2VPFwJiAhYARl6iMDN32Ih4", "name": "Sugar Lounge", "category": "Cocktail bar", "lng": -122.4225255, "lat": 37.7767776, "rating": 4.4, "reviewCount": 600, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 17, 25, 28, 25, 29, 37, 49, 49], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 25, 27, 31, 32, 38, 38, 33], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 28, 37, 40, 44, 52, 57, 50], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 18, 26, 36, 47, 52, 57, 45], [43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 25, 35, 44, 47, 52, 58, 64, 60], [72, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 36, 48, 64, 79, 93, 100, 100], [66, 43, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 33, 40, 46, 53, 68, 80, 85]], "carDependence": 0.029, "segmentId": "65325371_5352469999"}, {"id": "ChIJTRHt9JiAhYARIeAm-WG0inY", "name": "Phonobar", "category": "Bar", "lng": -122.4228274, "lat": 37.7779933, "rating": 4.3, "reviewCount": 431, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 30, 34, 32, 39, 50, 60, 71, 70, 70, 60, 45, 31], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 31, 40, 52, 60, 65, 58, 51, 35, 25], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 22, 30, 43, 51, 60, 49, 38, 25], [41, 29, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 41, 49, 50, 56, 72, 80, 80, 65], [59, 41, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 30, 40, 58, 74, 85, 88, 100, 98, 84], [57, 39, 0, 0, 0, 0, 0, 0, 0, 0, 0, 29, 36, 40, 47, 37, 40, 54, 72, 79, 84, 90, 91, 79]], "carDependence": 0.738, "segmentId": "65350745_5352470004"}, {"id": "ChIJp4nrB6KAhYARhS8cKd1vZ5Q", "name": "Biergarten", "category": "German restaurant", "lng": -122.4240612, "lat": 37.7760738, "rating": 4.4, "reviewCount": 1184, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 36, 56, 73, 88, 86, 68, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 19, 22, 22, 17, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 36, 41, 34, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 52, 59, 48, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 29, 40, 48, 44, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 46, 73, 92, 88, 63, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 64, 86, 100, 93, 77, 51, 0, 0, 0, 0]], "carDependence": 0.03, "segmentId": "65329081_298082887"}, {"id": "ChIJOSgJQJ-AhYAR5oEButf-LyE", "name": "San Francisco Wine & Cheese", "category": "Wine store", "lng": -122.4227447, "lat": 37.7747005, "rating": 4.9, "reviewCount": 184, "popularTimes": null, "carDependence": 0.24, "segmentId": "65304898_5352469988"}, {"id": "ChIJdYa7Y6KAhYARFMLxZvWvkhM", "name": "Wise Sons Jewish Deli Hayes Valley", "category": "Deli", "lng": -122.4248892, "lat": 37.7772722, "rating": 3.8, "reviewCount": 326, "popularTimes": [[0, 0, 0, 0, 0, 0, 0, 35, 44, 64, 55, 55, 47, 47, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 41, 64, 67, 58, 41, 35, 23, 17, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 26, 38, 61, 58, 61, 47, 41, 29, 0, 0, 0, 0, 0, 0, 0, 0, 0]
